# Environment Variables for Security-Sensitive Configuration
# These should be set in production environment or through secure configuration management
# Example: export CRYPTO_KEY="your-secure-key-here"
# Example: export MONGODB_PASSWORD="your-mongodb-password"
# Example: export KEYCLOAK_URL="https://your-keycloak-instance.com"

# Main Configuration
rule:
  container:
    name: ${RULE_CONTAINER_NAME}

cryptography:
  key: ${CRYPTO_KEY}
  iv: ${CRYPTO_IV}

spring:
  application:
    name: ${APP_NAME}
  data:
    mongodb:
      host: ${MONGODB_HOST}
      port: ${MONGODB_PORT}
      database: ${MONGODB_DATABASE}
      username: ${MONGODB_USERNAME}
      # password: ${MONGODB_PASSWORD:}
      authentication-database: ${MONGODB_AUTH_DATABASE}
      repositories.type: auto
      # MongoDB connection string (alternative to individual properties)
      uri: mongodb://${MONGODB_HOST}:${MONGODB_PORT}/${MONGODB_DATABASE}
  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE}
      max-request-size: ${MAX_REQUEST_SIZE}
  security:
    oauth2:
      authorizationserver:
        endpoint:
          jwk-set-uri: ${KEYCLOAK_URL}/realms/${KEYCLOAK_REALM}/protocol/openid-connect/certs
      resourceserver:
        jwt:
            issuer-uri: ${KEYCLOAK_URL}/realms/${KEYCLOAK_REALM}
server:
  port: ${SERVER_PORT}
  servlet:
    context-path: ${SERVER_CONTEXT_PATH}
spring-doc:
  open-api:
    info:
      version: "1.0.0"
      title: "BEAS Rule Engine"
      description: "BEAS Software Solution Rule Engine"
      summary: "This project made for preparation of the Rule Engine."
      termsOfService: https://beassolution.com/termOfService
      license:
        url: https://beassolution.com/rule-engine-license
        identifier: "®Copyright"
        name: "BEAS Licence"
      contact:
        email: contact@beassolution.com
        name: BEAS Solution
        url: https://ruleapp.beassolution.com